name: Build

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - run: npm install
            - run: npm run build
            - uses: actions/upload-artifact@v1
              with:
                  name: chrome-extension-stream-together
                  path: dist/
